[package]
name = "wintag"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
    "Win32_UI_Accessibility",
    "Win32_Graphics_Gdi",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_System_Com",
    "Win32_UI_Shell",
    "Win32_Graphics_Dwm",
    "Win32_System_Registry",
    "Win32_System_Console",
    "Win32_Security",
] }
anyhow = "1"
thiserror = "1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tray-icon = "0.24"
notify-rust = "4"
iced = { version = "0.13", default-features = false, features = ["tiny-skia", "multi-window", "smol"] }
crossbeam-channel = "0.5.16"

[build-dependencies]
winresource = "0.1.31"
